
name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Zip backend code
      run: |
        cd backend
        zip ../terraform/main.py.zip main.py

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.13.5

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: eu-north-1

    - name: Create tfvars file
      run: |
        echo "domain_name=\"${{ secrets.DOMAIN_NAME }}\"" > terraform/terraform.tfvars
        echo "project_name=\"cloud-resume-challenge\"" >> terraform/terraform.tfvars
        echo "aws_region=\"eu-north-1\"" >> terraform/terraform.tfvars
      
    - name: Terraform Init
      id: init
      run: |
        rm -f terraform.tfstate
        terraform init -input=false -reconfigure
      working-directory: ./terraform

    - name: Terraform Validate
      id: validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      working-directory: ./terraform

    - name: Get All Terraform Outputs as JSON
      id: get_tf_outputs
      run: |
        echo "terraform_outputs=$(terraform output -json)" >> $GITHUB_OUTPUT
      working-directory: ./terraform

    - name: Upload frontend to S3
      run: aws s3 sync frontend/ s3://${{ fromJson(steps.get_tf_outputs.outputs.terraform_outputs).s3_bucket_name }} --delete

    - name: CloudFront Cache Invalidation
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ fromJson(steps.get_tf_outputs.outputs.terraform_outputs).cloudfront_distribution_id }} --paths "/*"
      working-directory: ./terraform
